In [1]:
##Importamos librerias 

import pandas as pd
import numpy as np
import requests
import warnings 

pd.set_option('display.max_columns', None)

In [2]:
## DF OMOPHOBIA: 
## Fuente:

In [3]:
df_omophobia = pd.read_csv('/Users/veronicasanchez/Desktop/COPIA PROYECTO GRUPO3/files/omophobia.csv', encoding="latin1", delimiter=";")
df_omophobia.head(10)

,COUNTRY,CSSSA LEGAL?,DATE OF DECRIM,MAX PENALTY,CONST.,BROAD PROT.,EMPLOY.,HATE CRIME,INCITEMENT,BAN CONV. THERAPIES,SAME SEX MARRIAGE,CIVIL UNIONS,JOINT ADOPTION,SECOND PARENT ADOPTION
0,Algeria,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
1,Angola,YES,2021,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO
2,Benin,YES,NEVER CRIM,-,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
3,Botswana,YES,2019,-,NO,NO,YES,NO,NO,NO,NO,NO,NO,NO
4,Burkina Faso,YES,NEVER CRIM,-,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
5,Burundi,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
6,Cameroon,NO,-,5,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
7,Cabo Verde,YES,2004,-,NO,NO,YES,YES,NO,NO,NO,NO,NO,NO
8,Central Africa Republic,YES,NEVER CRIM,-,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
9,Chad,NO,-,2,NO,NO,NO,YES,NO,NO,NO,NO,NO,NO

In [4]:
df_omophobia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   COUNTRY                 241 non-null    object
 1   CSSSA LEGAL?            241 non-null    object
 2   DATE OF DECRIM          240 non-null    object
 3   MAX PENALTY             241 non-null    object
 4   CONST.                  197 non-null    object
 5   BROAD PROT.             241 non-null    object
 6   EMPLOY.                 241 non-null    object
 7   HATE CRIME              241 non-null    object
 8   INCITEMENT              241 non-null    object
 9   BAN CONV. THERAPIES     241 non-null    object
 10  SAME SEX MARRIAGE       241 non-null    object
 11  CIVIL UNIONS            241 non-null    object
 12  JOINT ADOPTION          241 non-null    object
 13  SECOND PARENT ADOPTION  241 non-null    object
dtypes: object(14)
memory usage: 26.5+ KB

In [5]:
## DF RAINBOW
## Fuente: https://rainbowmap.ilga-europe.org/

In [6]:
df_rainbow_map = pd.read_csv('/Users/veronicasanchez/Desktop/COPIA PROYECTO GRUPO3/files/2024-rainbow-map-data.csv', index_col=0)
df_rainbow_map.head(4)

,COUNTRIES,RANKING,Equality & non-discrimination,Equality & non-discrimination.1,Equality & non-discrimination.2,Equality & non-discrimination.3,Equality & non-discrimination.4,Equality & non-discrimination.5,Equality & non-discrimination.6,Equality & non-discrimination.7,Equality & non-discrimination.8,Equality & non-discrimination.9,Equality & non-discrimination.10,Equality & non-discrimination.11,Equality & non-discrimination.12,Equality & non-discrimination.13,Equality & non-discrimination.14,Equality & non-discrimination.15,Equality & non-discrimination.16,Equality & non-discrimination.17,Equality & non-discrimination.18,Equality & non-discrimination.19,Equality & non-discrimination.20,Equality & non-discrimination.21,Equality & non-discrimination.22,Equality & non-discrimination.23,Equality & non-discrimination.24,Family,Family.1,Family.2,Family.3,Family.4,Family.5,Family.6,Family.7,Family.8,Family.9,Family.10,Hate crime & hate speech,Hate crime & hate speech.1,Hate crime & hate speech.2,Hate crime & hate speech.3,Hate crime & hate speech.4,Hate crime & hate speech.5,Hate crime & hate speech.6,Hate crime & hate speech.7,Legal gender recognition,Legal gender recognition.1,Legal gender recognition.2,Legal gender recognition.3,Legal gender recognition.4,Legal gender recognition.5,Legal gender recognition.6,Legal gender recognition.7,Legal gender recognition.8,Legal gender recognition.9,Legal gender recognition.10,Legal gender recognition.11,Legal gender recognition.12,Legal gender recognition.13,Legal gender recognition.14,Intersex bodily integrity,Intersex bodily integrity.1,Intersex bodily integrity.2,Intersex bodily integrity.3,Civil society space,Civil society space.1,Civil society space.2,Civil society space.3,Civil society space.4,Civil society space.5,Asylum,Asylum.1,Asylum.2,Asylum.3,Asylum.4,Asylum.5
ABR,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
NaN,NaN,NaN,Constitution (sexual orientation),Employment (sexual orientation),Goods & services (sexual orientation),Education (sexual orientation),Health (sexual orientation),Conversion practices ban (sexual orientation),Equality body mandate (sexual orientation),Equality action plan (sexual orientation),Constitution (gender identity),Employment (gender identity),Goods & services (gender identity),Education (gender identity),Health (gender identity),Conversion practices ban (gender identity),Equality body mandate (gender identity),Equality action plan (gender identity),Law (gender expression),Constitution (sex characteristics),Employment (sex characteristics),Goods & services (sex characteristics),Education (sex characteristics),Health (sex characteristics),Equality body mandate (sex characteristics),Equality action plan (sex characteristics),Blood donations,Marriage equality,Registered partnership (similar rights to marr...,Registered partnership (limited rights),Cohabitation,No constitutional limitation on marriage,Joint adoption,Second-parent adoption,Automatic co-parent recognition,Medically assisted insemination (couples),Medically assisted insemination (singles),Recognition of trans parenthood,Hate crime law (sexual orientation),Hate speech law (sexual orientation),Policy tackling hatred (sexual orientation),Hate crime law (gender identity),Hate speech law (gender identity),Policy tackling hatred (gender identity),Hate crime law (intersex),Policies tackling hatred (intersex),No legal framework making legal gender recogni...,Existence of legal measures,Existence of administrative procedures,Name change,"No age restriction, Name change",Self-determination,Non-binary recognition,No 'Gender Identity Disorder' diagnosis/psycho...,No compulsory medical intervention required,No compulsory surgical intervention required,No compulsory sterilisation required,No compulsory divorce required,No age restriction,Legal gender recognition procedures exist for ...,Depathologisation,Prohibition of medical intervention without in...,Universality of prohibition of medical interve...,Existence of effective monitoring mechanism,Access to justice for victims and reparations,"Public event held, no state obstruction of fre...","Public event held, there is enough protection ...","Associations operate, no state obstruction of ...",LGBTI human rights defenders are not at risk,No laws limiting external funding,No laws limiting freedom of expression (nation...,Asylum law (sexual orientation),Other positive measures (sexual orientation),Asylum law (gender identity),Other positive measures (gender identity),Asylum law (intersex),Other positive measures (intersex)
NaN,NaN,NaN,"0,16%","1,10%","1,10%","1,10%","1,10%","0,80%","0,78%","0,88%","0,16%","1,10%","1,10%","1,10%","1,10%","0,80%","0,78%","0,88%","1,83%","0,16%","1,10%","1,10%","1,10%","1,10%","0,78%","0,88%","0,91%","3,75%","3,00%","2,00%","1,00%","0,75%","3,00%","1,75%","1,75%","2,00%","2,00%","2,50%","2,43%","2,43%","2,28%","2,43%","2,43%","2,28%","2,43%","2,28%","0,75%","1,50%","1,00%","1,00%","0,15%","2,00%","1,00%","1,75%","1,15%","1,15%","1,70%","1,05%","1,00%","0,30%","2,00%","2,50%","0,50%","1,00%","1,00%","1,50%","1,50%","1,50%","1,50%","1,50%","1,50%","1,50%","1,50%","1,50%","1,50%","1,50%","1,50%"
AL,Albania,"36,38",0,1,1,1,0,0,1,0,0,1,1,1,0,0,1,0,0,0,1,1,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,1,0,0,0
AD,Andorra,"43,23",1,1,1,1,1,0,1,0,0,1,1,1,1,0,1,0,1,0,0,0,0,0,0,0,0,1,1,1,0,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,1,1,0,0,1,1,1,1,1,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0

In [7]:
df_rainbow_map.shape

(51, 77)

In [8]:
df_rainbow_map['COUNTRIES'].count()

49

In [9]:
df_1 = pd.read_excel('/Users/veronicasanchez/Desktop/COPIA PROYECTO GRUPO3/files/_database_digital_rev.4_7_21.xlsx')
df_1

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,Column11,Column12,Column13,Column14,Column15,Column16,Column17,Column18,Column20,Column21,Column22,Column23,Column24,Column25,Column26,Column27,Column28,Column29,Column30,Column31
0,continent,sub contient,country,Predom. Religion,SOGI-LI,DEMOC.,HAPPINESS,Per capita GDP,% with tertiary educ.,GRI,Religiosity,SHI,legality of sam-sex sexual-activity,marriage/ civil unions,same-sex coupleadoptions,serving in the military,antidiscrimination laws,gender ID markers,Democracy Status,electoral process and pluralism,funct. Of gov,polit. Particpation,political culture,civil liberties,Satisfaction with GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
1,africa,6. S.Africa,Zimbabwe,C,0.42,3.16,3.692,2147,0.38,2.8,0.88,2.1,0.25,0,0,0,0,0,A,0.5,2,4.44,2.5,3.24,1.151,1.479,0.599,0.399,0.065,0.025
2,africa,6. S.Africa,Zambia,C,0.97,5.61,4.377,1539.9,0.49,3.2,0.95,2,0.25,0.33,0,0,0,0,H,6.17,4.64,3.89,5.63,4.41,0.493,1.048,0.454,0.504,0.352,0.055
3,asia,8. W. Asia,Yemen,M,0.56,1.95,3.355,944.41,1.5,4.7,0.99,7.2,0,0.33,0,0,0,0,A,0,0,3.89,5.63,3.24,0.357,1.094,0.248,0.406,0.132,0.099
4,asia,10. SE. Asia,Vietnam,x,3.89,3.08,5.103,2563.82,3.27,7.6,0.3,1.5,1,0.33,0,0.5,0,0.5,A,0,NaN,3.21,3.75,4.41,0.689,1.172,0.048,0.462,0.201,0.032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,africa,6. S.Africa,Angola,C,3.39,3.62,3.795,3432.39,NaN,4.1,0.88,3.2,1,0.33,0,0,0.2,0.5,A,1.75,2.86,5.56,8.75,10,1.33,1.532,0.896,0.653,0.321,0.291
181,europe,18. S. Europe,Andorra,C,5.28,NaN,NaN,42029.76,NaN,2.4,NaN,0,1,0.67,0.5,0,1,0,NaN,NaN,NaN,NaN,10,9.41,1.355,1.501,0.913,0.659,0.285,0.383
182,africa,3. N.Africa,Algeria,M,1.39,3.5,5.295,4278.85,6.66,8,0.95,6.3,0.5,0.33,0,0,0,0,A,2.58,2.21,3.89,9.38,9.12,1.351,1.59,0.868,0.683,0.284,0.408
183,europe,18. S. Europe,Albania,M,4.72,5.98,4.586,5253.63,0.93,1.6,0.39,0.1,1,0.33,0,0.5,1,0,H,7,4.71,5.56,8.13,9.12,1.301,1.559,0.883,0.533,0.354,0.272
184,asia,9. C. Asia,Afghanistan,M,0.56,2.97,3.632,520.9,NaN,6.5,0.97,6.9,0,0.33,0,0,0,0,A,2.92,1.14,4.44,5.63,8.53,1.293,1.466,0.908,0.52,0.098,0.176

In [10]:
## DF Tweets
## Fuente: https://www.kaggle.com/code/vencerlanz09/lgbt-tweets-eda-sentiment-analysis

In [11]:
df_tweets = pd.read_csv("/Users/veronicasanchez/Desktop/COPIA PROYECTO GRUPO3/files/LGBT_Tweets_processed.csv", index_col=0)
df_tweets

,date,time,id,tweet,language,replies_count,retweets_count,likes_count
0,2022-08-26,10:31:10,1562991009180827649,Praying for my lgbt Nigerians 🙏🏽🙏🏽🙏🏽,en,0,0,0
1,2022-08-26,10:31:02,1562990976939229184,@yanmisamm So pass agg omg you really are lgbt,en,0,0,0
3,2022-08-26,10:30:59,1562990965442326528,@ChampionExcel @watokohom @MrAndyNgo @football...,en,0,0,0
7,2022-08-26,10:30:34,1562990860928659457,To be clear it doesn't justify what the LGBT c...,en,0,0,0
10,2022-08-26,10:30:24,1562990819485032449,good night lgbt community https://t.co/0PAMOU...,en,1,0,2
...,...,...,...,...,...,...,...,...
99995,2022-08-21,00:09:11,1561022541833068545,@i664k @birdofterror4 @st1mmer @cringepolitik ...,en,0,1,1
99997,2022-08-21,00:09:06,1561022522933616642,@Comrade4568 I`m anti-trans and anti-lgbt,en,1,0,1
100009,2022-08-21,00:07:52,1561022211405881344,#Lgbt #lgbtq #lgbtqiaplus #lgbtqcommunity #lgb...,en,0,0,0
100010,2022-08-21,00:07:50,1561022206167187456,Man its no fucking wonder why it's so hard for...,en,1,0,0
100017,2022-08-21,00:07:09,1561022032858464256,REPUBLICANS BRAGGING ABOUT WHAT? Legislation:...,en,0,1,0

In [12]:
## DF Criminalizacion
## Fuente: https://www.humandignitytrust.org/lgbt-the-law/map-of-criminalisation/

In [13]:
df_criminalizacion = pd.read_csv('/Users/veronicasanchez/Desktop/COPIA PROYECTO GRUPO3/files/Criminalizacion_LGBT.csv')
df_criminalizacion

,País,Criminaliza a personas LGBT,Criminaliza actividad sexual entre hombres,Criminaliza actividad sexual entre mujeres,Criminaliza la expresión de género de personas trans,Impone la pena de muerte,Pena máxima
0,Afganistán,Sí,Sí,Sí,No,Sí,Pena de muerte
1,Bangladés,Sí,Sí,Sí,No,No,Cadena perpetua
2,Brunéi,Sí,Sí,Sí,Sí,Sí,Muerte por lapidación
3,Indonesia,Sí,Sí,Sí,Sí,No,Ocho años de prisión y 100 latigazos
4,Irán,Sí,Sí,Sí,No,Sí,Pena de muerte
...,...,...,...,...,...,...,...
59,San Vicente y las Granadinas,Sí,Sí,Sí,NaN,NaN,Diez años de prisión
60,Trinidad y Tobago,Sí,Sí,Sí,NaN,NaN,Diez años de prisión
61,Belice,Sí,Sí,Sí,NaN,NaN,Diez años de prisión
62,Dominicana,Sí,Sí,Sí,NaN,NaN,NaN
63,Jordania,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df_criminalizacion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 7 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   País                                                  64 non-null     object
 1   Criminaliza a personas LGBT                           63 non-null     object
 2   Criminaliza actividad sexual entre hombres            63 non-null     object
 3   Criminaliza actividad sexual entre mujeres            63 non-null     object
 4   Criminaliza la expresión de género de personas trans  59 non-null     object
 5   Impone la pena de muerte                              59 non-null     object
 6   Pena máxima                                           62 non-null     object
dtypes: object(7)
memory usage: 3.6+ KB

In [15]:
## DF Index
## Fuente: https://ourworldindata.org/grapher/lgbt-legal-equality-index

In [16]:
df_index = pd.read_csv('/Users/veronicasanchez/Desktop/COPIA PROYECTO GRUPO3/files/lgbt-legal-equality-index.csv')
df_index

          Entity      Code  Year   ei_legal
0    Afghanistan       AFG  2024   0.000000
1         Africa       NaN  2024  20.723385
2        Albania       ALB  2024  62.270000
3        Algeria       DZA  2024   3.420000
4        Andorra       AND  2024  85.710000
..           ...       ...   ...        ...
196      Vietnam       VNM  2024  58.180000
197        World  OWID_WRL  2024  49.721184
198        Yemen       YEM  2024   0.000000
199       Zambia       ZMB  2024  17.650000
200     Zimbabwe       ZWE  2024  33.030000

[201 rows x 4 columns]

In [17]:
df_index['Entity'].unique()

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Asia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
       'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus',
       'Czechia', 'Democratic Republic of Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Europe', 'Fiji', 'Finland', 'France',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (country)', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'North America', 'North Korea',
       'North Macedonia', 'Norway', 'Oceania', 'Oman', 'Pakistan',
       'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia',
       'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South America',
       'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
       'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Venezuela', 'Vietnam', 'World', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [18]:
df_omophobia.columns

Index(['COUNTRY', 'CSSSA LEGAL?', 'DATE OF DECRIM', 'MAX PENALTY', 'CONST.',
       'BROAD PROT.', 'EMPLOY.', 'HATE CRIME', 'INCITEMENT',
       'BAN CONV. THERAPIES', 'SAME SEX MARRIAGE', 'CIVIL UNIONS',
       'JOINT ADOPTION', 'SECOND PARENT ADOPTION'],
      dtype='object')

In [19]:

df_index.rename(columns={"Entity": 'COUNTRY'}, inplace=True)

In [20]:
df_index

         COUNTRY      Code  Year   ei_legal
0    Afghanistan       AFG  2024   0.000000
1         Africa       NaN  2024  20.723385
2        Albania       ALB  2024  62.270000
3        Algeria       DZA  2024   3.420000
4        Andorra       AND  2024  85.710000
..           ...       ...   ...        ...
196      Vietnam       VNM  2024  58.180000
197        World  OWID_WRL  2024  49.721184
198        Yemen       YEM  2024   0.000000
199       Zambia       ZMB  2024  17.650000
200     Zimbabwe       ZWE  2024  33.030000

[201 rows x 4 columns]

In [21]:

df_unido = pd.merge(df_index, df_omophobia, on='COUNTRY', how='outer', indicator=True)

# Ver los países que están solo en df1
solo_en_df_index = df_unido[df_unido['_merge'] == 'left_only']

# Ver los países que están solo en df2
solo_en_df_omophobia = df_unido[df_unido['_merge'] == 'right_only']

# Ver los países comunes en ambos DataFrames
mismos_paises = df_unido[df_unido['_merge'] == 'both']

In [22]:
mismos_paises.head(5)

,COUNTRY,Code,Year,ei_legal,CSSSA LEGAL?,DATE OF DECRIM,MAX PENALTY,CONST.,BROAD PROT.,EMPLOY.,HATE CRIME,INCITEMENT,BAN CONV. THERAPIES,SAME SEX MARRIAGE,CIVIL UNIONS,JOINT ADOPTION,SECOND PARENT ADOPTION,_merge
0,Afghanistan,AFG,2024.0,0.00,NO,-,DEATH (P),NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
2,Albania,ALB,2024.0,62.27,YES,1995,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO,both
3,Algeria,DZA,2024.0,3.42,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
5,Andorra,AND,2024.0,85.71,YES,1990,-,NO,YES,YES,YES,NO,NO,NO,YES,YES,YES,both
6,Angola,AGO,2024.0,66.19,YES,2021,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO,both

In [23]:
solo_en_df_omophobia.head(5)

,COUNTRY,Code,Year,ei_legal,CSSSA LEGAL?,DATE OF DECRIM,MAX PENALTY,CONST.,BROAD PROT.,EMPLOY.,HATE CRIME,INCITEMENT,BAN CONV. THERAPIES,SAME SEX MARRIAGE,CIVIL UNIONS,JOINT ADOPTION,SECOND PARENT ADOPTION,_merge
4,American Samoa (USA),NaN,NaN,NaN,YES,1980,-,NaN,NO,NO,NO,NO,NO,NO,NO,NO,NO,right_only
7,Anguilla (UK),NaN,NaN,NaN,YES,2001,-,NaN,NO,NO,LIMITED,NO,NO,NO,NO,NO,NO,right_only
11,Aruba (NL),NaN,NaN,NaN,YES,1869,-,NaN,YES,YES,NO,YES,NO,NO,YES,NO,NO,right_only
24,Bermuda (UK),NaN,NaN,NaN,YES,1994,-,NaN,YES,YES,YES,YES,NO,NO,NO,YES,YES,right_only
27,Bonaire (NL),NaN,NaN,NaN,YES,1869,-,NaN,YES,YES,NO,YES,NO,YES,YES,NO,NO,right_only

In [24]:
solo_en_df_index.head(5)

,COUNTRY,Code,Year,ei_legal,CSSSA LEGAL?,DATE OF DECRIM,MAX PENALTY,CONST.,BROAD PROT.,EMPLOY.,HATE CRIME,INCITEMENT,BAN CONV. THERAPIES,SAME SEX MARRIAGE,CIVIL UNIONS,JOINT ADOPTION,SECOND PARENT ADOPTION,_merge
1,Africa,NaN,2024.0,20.723385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
12,Asia,NaN,2024.0,48.204490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
29,Bosnia and Herzegovina,BIH,2024.0,63.330000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
34,Brunei,BRN,2024.0,6.830000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
43,Cape Verde,CPV,2024.0,51.220000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [25]:
df_unido

,COUNTRY,Code,Year,ei_legal,CSSSA LEGAL?,DATE OF DECRIM,MAX PENALTY,CONST.,BROAD PROT.,EMPLOY.,HATE CRIME,INCITEMENT,BAN CONV. THERAPIES,SAME SEX MARRIAGE,CIVIL UNIONS,JOINT ADOPTION,SECOND PARENT ADOPTION,_merge
0,Afghanistan,AFG,2024.0,0.000000,NO,-,DEATH (P),NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
1,Africa,NaN,2024.0,20.723385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,Albania,ALB,2024.0,62.270000,YES,1995,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO,both
3,Algeria,DZA,2024.0,3.420000,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
4,American Samoa (USA),NaN,NaN,NaN,YES,1980,-,NaN,NO,NO,NO,NO,NO,NO,NO,NO,NO,right_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,Wallis and Futuna (FR),NaN,NaN,NaN,YES,NEVER CRIM,-,NaN,YES,YES,YES,YES,NO,YES,YES,YES,YES,right_only
257,World,OWID_WRL,2024.0,49.721184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
258,Yemen,YEM,2024.0,0.000000,NO,-,DEATH,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
259,Zambia,ZMB,2024.0,17.650000,NO,-,FOR LIFE,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
260,Zimbabwe,ZWE,2024.0,33.030000,NO,-,1,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both

In [26]:
df_unido.columns

Index(['COUNTRY', 'Code', 'Year', 'ei_legal', 'CSSSA LEGAL?', 'DATE OF DECRIM',
       'MAX PENALTY', 'CONST.', 'BROAD PROT.', 'EMPLOY.', 'HATE CRIME',
       'INCITEMENT', 'BAN CONV. THERAPIES', 'SAME SEX MARRIAGE',
       'CIVIL UNIONS', 'JOINT ADOPTION', 'SECOND PARENT ADOPTION', '_merge'],
      dtype='object')

In [27]:
# Eliminamos las columnas 'Code' y '_merge'
df_unido.drop(columns=['Code', '_merge'], inplace=True)

In [28]:
# Guardamos los cambios
df_unido.rename(columns=lambda x: x.lower(), inplace=True)

In [29]:
df_unido.head()

,country,year,ei_legal,csssa legal?,date of decrim,max penalty,const.,broad prot.,employ.,hate crime,incitement,ban conv. therapies,same sex marriage,civil unions,joint adoption,second parent adoption
0,Afghanistan,2024.0,0.000000,NO,-,DEATH (P),NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
1,Africa,2024.0,20.723385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,2024.0,62.270000,YES,1995,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO
3,Algeria,2024.0,3.420000,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
4,American Samoa (USA),NaN,NaN,YES,1980,-,NaN,NO,NO,NO,NO,NO,NO,NO,NO,NO

In [30]:
df_unido.dtypes

country                    object
year                      float64
ei_legal                  float64
csssa legal?               object
date of decrim             object
max penalty                object
const.                     object
broad prot.                object
employ.                    object
hate crime                 object
incitement                 object
ban conv. therapies        object
same sex marriage          object
civil unions               object
joint adoption             object
second parent adoption     object
dtype: object

In [31]:
df_unido.isnull().mean() * 100

country                    0.000000
year                      22.988506
ei_legal                  22.988506
csssa legal?               7.662835
date of decrim             8.045977
max penalty                7.662835
const.                    24.521073
broad prot.                7.662835
employ.                    7.662835
hate crime                 7.662835
incitement                 7.662835
ban conv. therapies        7.662835
same sex marriage          7.662835
civil unions               7.662835
joint adoption             7.662835
second parent adoption     7.662835
dtype: float64

In [32]:
# Cambiamos los nombres de las columnas
columns_originales = [
    'country', 'year', 'ei_legal', 'csssa legal?', 'date of decrim',
    'max penalty', 'const.', 'broad prot.', 'employ.', 'hate crime',
    'incitement', 'ban conv. therapies', 'same sex marriage',
    'civil unions', 'joint adoption', 'second parent adoption'
]
df_unido = pd.DataFrame(df_unido, columns=columns_originales)

nuevos_nombres = [
    'país', 'año_actualización_datos', 'índice de igualdad legal', 'legalidad_colectivo_lgbtiq+', 'fecha_despenalización',
    'pena_máxima', 'constitución', 'protección_amplia', 'empleo', 'crimen_odio',
    'incitación', 'prohibición_terapias', 'matrimonio_igualitario',
    'uniones_civiles', 'adopción_conjunta', 'adopción_segundo_progenitor']

# Aplicar los nuevos nombres
df_unido.columns = nuevos_nombres

In [33]:
df_unido.head()

,país,año_actualización_datos,índice de igualdad legal,legalidad_colectivo_lgbtiq+,fecha_despenalización,pena_máxima,constitución,protección_amplia,empleo,crimen_odio,incitación,prohibición_terapias,matrimonio_igualitario,uniones_civiles,adopción_conjunta,adopción_segundo_progenitor
0,Afghanistan,2024.0,0.000000,NO,-,DEATH (P),NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
1,Africa,2024.0,20.723385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,2024.0,62.270000,YES,1995,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO
3,Algeria,2024.0,3.420000,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
4,American Samoa (USA),NaN,NaN,YES,1980,-,NaN,NO,NO,NO,NO,NO,NO,NO,NO,NO

In [34]:
df_unido.shape

(261, 16)

In [35]:
# Quitamos los que no eran países

no_paises = [
    "Africa",
    "American Samoa (USA)",
    "Anguilla (UK)",
    "Aruba (NL)",
    "Asia",
    "Bermuda (UK)",
    "Bonaire (NL)",
    "British Indian Terr. (UK)",
    "British Virgin Islands (UK)",
    "Cape Verde",  # (duplicado de Cabo Verde)
    "Cayman Islands (UK)",
    "Central Africa Republic",
    "Cook Islands (NZ)",
    "Curacao (NL)",
    "DRC",  # (abreviatura de Democratic Republic of Congo)
    "Europe",
    "Falkland/Malv. (UK/AR)",
    "Faroe Islands (DN)",
    "French Guiana (FR)",
    "French Polynesia (FR)",
    "Gibraltar (UK)",
    "Greenland (DN)",
    "Guadeloupe (FR)",
    "Guam (USA)",
    "Guernsey (UK)",
    "Hong Kong (SAR China)",
    "Indonesia1",  # (error tipográfico de Indonesia)
    "Isle of Man (UK)",
    "Jersey (UK)",
    "Macau (China)",
    "Martinique (FR)",
    "Mayotte (FR)",
    "Micronesia (country)",  # (duplicado de Micronesia)
    "Montserrat (UK)",
    "New Caledonia (FR)",
    "Niue (NZ)",
    "North America",
    "Oceania",
    "Pitcairn Islands (UK)",
    "North. Mariana Is. (USA)",
    "Puerto Rico (USA)",
    "Reunion (FR)",
    "Saba (NL)",
    "Saint Barthelemy (FR)",
    "Saint Martin (FR)",
    "Saint Pierre et Miq. (FR)",
    "Sint Eustatius (NL)",
    "Sint Maarten (NL)",
    "South America",
    "South Georg. & Sand. (UK)",
    "St. Helena, Asc., TdA (UK)",
    "Taiwan (China)",  # (duplicado de Taiwan)
    "Tokelau (NZ)",
    "Turks and Caicos (UK)",
    "US Virgin Islands (USA)",
    "Wallis and Futuna (FR)",
    "World"
]

df_unido2 = df_unido[~df_unido['país'].isin(no_paises)]

In [36]:
df_unido2.shape

(204, 16)

In [37]:
# Miramos los valores únicos de la columna 'año_actualización_datos'
df_unido['año_actualización_datos'].unique()

array([2024.,   nan])

In [38]:
# Sacamos la moda para reemplazar los nulos de la columna
moda=df_unido2["año_actualización_datos"].mode()[0]

In [39]:
# Reemplazamos los nulos con la moda
df_unido2["año_actualización_datos"] = df_unido2["año_actualización_datos"].fillna(moda)

/var/folders/_8/rv04zc812vngdv98w27kqfbw0000gp/T/ipykernel_7659/2267746775.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unido2["año_actualización_datos"] = df_unido2["año_actualización_datos"].fillna(moda)

In [40]:
df_unido2["año_actualización_datos"].isnull().sum()

0

In [41]:
df_unido2['país'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia & Herzegovina', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Czechia',
       "Côte d'Ivoire", 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'East Timor',
       'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro',
       'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'North Korea', 'North Macedonia', 'Norway', 'Oman', 'Pakistan',
       'Palau', 'Palestine2', 'Panama', 'Papua New Guinea', 'Paraguay',
       'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania',
       'Russia', 'Rwanda', 'Saint Kitts & Nevis', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vinc. & the Gren.',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome & Principe', 'Sao Tome and Principe', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
       'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka',
       'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam', 'Yemen',
       'Zambia', 'Zimbabwe'], dtype=object)

In [42]:
# Corregimos el nombre de Palestina
df_unido2['país'] = df_unido2['país'].replace('Palestine2', 'Palestine')

/var/folders/_8/rv04zc812vngdv98w27kqfbw0000gp/T/ipykernel_7659/1790357689.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unido2['país'] = df_unido2['país'].replace('Palestine2', 'Palestine')

In [43]:
df_unido2['país'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia & Herzegovina', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Czechia',
       "Côte d'Ivoire", 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'East Timor',
       'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro',
       'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'North Korea', 'North Macedonia', 'Norway', 'Oman', 'Pakistan',
       'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay',
       'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania',
       'Russia', 'Rwanda', 'Saint Kitts & Nevis', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vinc. & the Gren.',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome & Principe', 'Sao Tome and Principe', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
       'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka',
       'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam', 'Yemen',
       'Zambia', 'Zimbabwe'], dtype=object)

In [44]:
df_unido2.isnull().mean() * 100

país                           0.000000
año_actualización_datos        0.000000
índice de igualdad legal       5.882353
legalidad_colectivo_lgbtiq+    5.392157
fecha_despenalización          5.882353
pena_máxima                    5.392157
constitución                   5.392157
protección_amplia              5.392157
empleo                         5.392157
crimen_odio                    5.392157
incitación                     5.392157
prohibición_terapias           5.392157
matrimonio_igualitario         5.392157
uniones_civiles                5.392157
adopción_conjunta              5.392157
adopción_segundo_progenitor    5.392157
dtype: float64

In [45]:
df_unido2.dtypes

país                            object
año_actualización_datos        float64
índice de igualdad legal       float64
legalidad_colectivo_lgbtiq+     object
fecha_despenalización           object
pena_máxima                     object
constitución                    object
protección_amplia               object
empleo                          object
crimen_odio                     object
incitación                      object
prohibición_terapias            object
matrimonio_igualitario          object
uniones_civiles                 object
adopción_conjunta               object
adopción_segundo_progenitor     object
dtype: object

In [46]:
# Cambiamos el tipo de datos de la columna "año_actualización_datos"
df_unido2['año_actualización_datos'] = df_unido2['año_actualización_datos'].astype(int)

/var/folders/_8/rv04zc812vngdv98w27kqfbw0000gp/T/ipykernel_7659/323974521.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unido2['año_actualización_datos'] = df_unido2['año_actualización_datos'].astype(int)

In [47]:
df_unido2.dtypes

país                            object
año_actualización_datos          int64
índice de igualdad legal       float64
legalidad_colectivo_lgbtiq+     object
fecha_despenalización           object
pena_máxima                     object
constitución                    object
protección_amplia               object
empleo                          object
crimen_odio                     object
incitación                      object
prohibición_terapias            object
matrimonio_igualitario          object
uniones_civiles                 object
adopción_conjunta               object
adopción_segundo_progenitor     object
dtype: object

In [48]:
df_unido2.head()

,país,año_actualización_datos,índice de igualdad legal,legalidad_colectivo_lgbtiq+,fecha_despenalización,pena_máxima,constitución,protección_amplia,empleo,crimen_odio,incitación,prohibición_terapias,matrimonio_igualitario,uniones_civiles,adopción_conjunta,adopción_segundo_progenitor
0,Afghanistan,2024,0.00,NO,-,DEATH (P),NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
2,Albania,2024,62.27,YES,1995,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO
3,Algeria,2024,3.42,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
5,Andorra,2024,85.71,YES,1990,-,NO,YES,YES,YES,NO,NO,NO,YES,YES,YES
6,Angola,2024,66.19,YES,2021,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO

In [49]:
df_unido2['pena_máxima'].unique()

array(['DEATH (P)', '-', '2', '15', '10', 'FOR LIFE', '1', nan, '5',
       'UNDETERM.', '7', '3', '14', 'DEATH', '20', '8', 'VARIES'],
      dtype=object)

In [50]:
# Diccionario para valores específicos
reemplazos = {
    'DEATH': 'Pena de muerte',
    'DEATH (P)': 'Pena de muerte',
    '-': 'Desconocido',
    np.nan: 'Desconocido',  # np.nan también se puede mapear con replace
    'FOR LIFE': 'Cadena perpetua',
    'VARIES': 'Varía',
    'UNDETERM.' : 'Indeterminado'
}
# Reemplazar valores directos con el diccionario
df_unido2['pena_máxima'] = df_unido2['pena_máxima'].replace(reemplazos)
# Añadir "años" a los números y procesar casos restantes
df_unido2['pena_máxima'] = df_unido2['pena_máxima'].apply(lambda x: f"{x} años" if str(x).isdigit() else x)

/var/folders/_8/rv04zc812vngdv98w27kqfbw0000gp/T/ipykernel_7659/3384167008.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unido2['pena_máxima'] = df_unido2['pena_máxima'].replace(reemplazos)
/var/folders/_8/rv04zc812vngdv98w27kqfbw0000gp/T/ipykernel_7659/3384167008.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unido2['pena_máxima'] = df_unido2['pena_máxima'].apply(lambda x: f"{x} años" if str(x).isdigit() else x)

In [51]:
df_unido2['pena_máxima'].unique()

array(['Pena de muerte', 'Desconocido', '2 años', '15 años', '10 años',
       'Cadena perpetua', '1 años', '5 años', 'Indeterminado', '7 años',
       '3 años', '14 años', '20 años', '8 años', 'Varía'], dtype=object)

In [52]:
# Procedemos a homogeneizar los datos

reemplazos1 = {
    'YES': 'Si',
    'NO': 'No',
    'LIMITED': 'Limitada'
}
# Lista de columnas donde aplicar los reemplazos
columnas_a_modificar = [
    "legalidad_colectivo_lgbtiq+", "fecha_despenalización", "constitución",
    "protección_amplia", "empleo", "crimen_odio", "incitación",
    "prohibición_terapias", "matrimonio_igualitario", "uniones_civiles",
    "adopción_conjunta", "adopción_segundo_progenitor"
]
# Reemplazar valores en las columnas seleccionadas
df_unido2[columnas_a_modificar] = df_unido2[columnas_a_modificar].replace(reemplazos1)

/var/folders/_8/rv04zc812vngdv98w27kqfbw0000gp/T/ipykernel_7659/1708812090.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unido2[columnas_a_modificar] = df_unido2[columnas_a_modificar].replace(reemplazos1)

In [53]:
df_unido2.head()

,país,año_actualización_datos,índice de igualdad legal,legalidad_colectivo_lgbtiq+,fecha_despenalización,pena_máxima,constitución,protección_amplia,empleo,crimen_odio,incitación,prohibición_terapias,matrimonio_igualitario,uniones_civiles,adopción_conjunta,adopción_segundo_progenitor
0,Afghanistan,2024,0.00,No,-,Pena de muerte,No,No,No,No,No,No,No,No,No,No
2,Albania,2024,62.27,Si,1995,Desconocido,No,Si,Si,Si,Si,No,No,No,No,No
3,Algeria,2024,3.42,No,-,2 años,No,No,No,No,No,No,No,No,No,No
5,Andorra,2024,85.71,Si,1990,Desconocido,No,Si,Si,Si,No,No,No,Si,Si,Si
6,Angola,2024,66.19,Si,2021,Desconocido,No,Si,Si,Si,Si,No,No,No,No,No

In [54]:
# Eliminamos la columna 'año_actualización_datos' porq todos los datos son iguales "2024"
df_unido2.drop(columns=['año_actualización_datos'], inplace=True)
# Guardamos los cambios
df_unido2.rename(columns=lambda x: x.lower(), inplace=True)

/var/folders/_8/rv04zc812vngdv98w27kqfbw0000gp/T/ipykernel_7659/1772774502.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unido2.drop(columns=['año_actualización_datos'], inplace=True)
/var/folders/_8/rv04zc812vngdv98w27kqfbw0000gp/T/ipykernel_7659/1772774502.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unido2.rename(columns=lambda x: x.lower(), inplace=True)

In [55]:
df_unido2['fecha_despenalización'].unique()

array(['-', '1995', '1990', '2021', '1903', '2003', '1975-1997', '1971',
       '2000', '1991', '1976', '1994', '1795', '2016', 'NEVER CRIM',
       '1832', '1991-2003', nan, '2019', '1831', '1968', '2004', '1969',
       '1999', '1997', '1981', '1977', '1979', '1998', '1962', '1933',
       '1822', '1975', '1826', '1992', '2010', '1791', '2020',
       '1968-1969', '1951', '1834', '1993', '1899', '1940', '2018',
       '1988', '1890', '1882', '2012', '1989', '1973', '2005', '1872',
       '1793', '1961', '2015', '2007', '1811', '1986', '2008', '1996',
       '1972', '2014', '1924', '1870', '1932', '1983', '1869', '1944',
       '1942', '1957', '1858', '1967-1982', '1962-2003', '1934', '1836'],
      dtype=object)

In [56]:
df_unido2[df_unido2['fecha_despenalización'] == 'NEVER CRIM']

,país,índice de igualdad legal,legalidad_colectivo_lgbtiq+,fecha_despenalización,pena_máxima,constitución,protección_amplia,empleo,crimen_odio,incitación,prohibición_terapias,matrimonio_igualitario,uniones_civiles,adopción_conjunta,adopción_segundo_progenitor
23,Benin,43.81,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
37,Burkina Faso,52.22,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
40,Cambodia,53.89,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
52,Congo,43.81,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
62,Côte d'Ivoire,NaN,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
66,Djibouti,32.82,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
73,Equatorial Guinea,48.57,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
126,Laos,49.47,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
136,Madagascar,43.81,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
140,Mali,32.73,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
148,Micronesia,NaN,Si,NEVER CRIM,Desconocido,No,Si,Si,No,No,No,No,No,No,No
165,Niger,40.50,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
169,North Korea,38.33,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
191,Rwanda,45.00,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
220,South Korea,48.33,Si,NEVER CRIM,Desconocido,No,Limitada,Limitada,No,No,No,No,No,No,No
252,Vanuatu,60.53,Si,NEVER CRIM,Desconocido,No,No,Limitada,No,No,No,No,No,No,No
255,Vietnam,58.18,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No

In [57]:
# Buscamos cuáles son los países que tiene 'NEVER CRIM'
df_unido2[df_unido2['fecha_despenalización'] == 'NEVER CRIM']['país']

23                 Benin
37          Burkina Faso
40              Cambodia
52                 Congo
62         Côte d'Ivoire
66              Djibouti
73     Equatorial Guinea
126                 Laos
136           Madagascar
140                 Mali
148           Micronesia
165                Niger
169          North Korea
191               Rwanda
220          South Korea
252              Vanuatu
255              Vietnam
Name: país, dtype: object

In [58]:
df_unido2[df_unido2['fecha_despenalización'] == '-']

,país,índice de igualdad legal,legalidad_colectivo_lgbtiq+,fecha_despenalización,pena_máxima,constitución,protección_amplia,empleo,crimen_odio,incitación,prohibición_terapias,matrimonio_igualitario,uniones_civiles,adopción_conjunta,adopción_segundo_progenitor
0,Afghanistan,0.00,No,-,Pena de muerte,No,No,No,No,No,No,No,No,No,No
3,Algeria,3.42,No,-,2 años,No,No,No,No,No,No,No,No,No,No
8,Antigua and Barbuda,84.21,No,-,15 años,No,No,No,Limitada,No,No,No,No,No,No
18,Bangladesh,23.25,No,-,10 años,No,No,No,No,No,No,No,No,No,No
19,Barbados,54.76,No,-,Cadena perpetua,No,No,Si,No,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,United Arab Emirates,4.88,No,-,Pena de muerte,No,No,No,No,No,No,No,No,No,No
251,Uzbekistan,20.83,No,-,3 años,No,No,No,No,No,No,No,No,No,No
258,Yemen,0.00,No,-,Pena de muerte,No,No,No,No,No,No,No,No,No,No
259,Zambia,17.65,No,-,Cadena perpetua,No,No,No,No,No,No,No,No,No,No
260,Zimbabwe,33.03,No,-,1 años,No,No,No,No,No,No,No,No,No,No

In [59]:
df_unido2[df_unido2['fecha_despenalización'] == '-']['país']

0               Afghanistan
3                   Algeria
8       Antigua and Barbuda
18               Bangladesh
19                 Barbados
               ...
247    United Arab Emirates
251              Uzbekistan
258                   Yemen
259                  Zambia
260                Zimbabwe
Name: país, Length: 68, dtype: object

In [60]:
# Cambiamos fechas coherentes
df_unido2['fecha_despenalización'] = df_unido2['fecha_despenalización'].replace({
    '-': '0', 
    'NEVER CRIM': '0000', 
    '1975-1997': '1997', 
    '1991-2003': '2003',
    '1968-1969': '1969',
    '1967-1982': '1982',
    '1962-2003': '2003'
})

/var/folders/_8/rv04zc812vngdv98w27kqfbw0000gp/T/ipykernel_7659/284760656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unido2['fecha_despenalización'] = df_unido2['fecha_despenalización'].replace({

In [61]:
df_unido2['fecha_despenalización'].unique()

array(['0', '1995', '1990', '2021', '1903', '2003', '1997', '1971',
       '2000', '1991', '1976', '1994', '1795', '2016', '0000', '1832',
       nan, '2019', '1831', '1968', '2004', '1969', '1999', '1981',
       '1977', '1979', '1998', '1962', '1933', '1822', '1975', '1826',
       '1992', '2010', '1791', '2020', '1951', '1834', '1993', '1899',
       '1940', '2018', '1988', '1890', '1882', '2012', '1989', '1973',
       '2005', '1872', '1793', '1961', '2015', '2007', '1811', '1986',
       '2008', '1996', '1972', '2014', '1924', '1870', '1932', '1983',
       '1869', '1944', '1942', '1957', '1858', '1982', '1934', '1836'],
      dtype=object)

In [62]:
df_unido2.isnull().sum() / df_unido2.shape[0] * 100

país                           0.000000
índice de igualdad legal       5.882353
legalidad_colectivo_lgbtiq+    5.392157
fecha_despenalización          5.882353
pena_máxima                    0.000000
constitución                   5.392157
protección_amplia              5.392157
empleo                         5.392157
crimen_odio                    5.392157
incitación                     5.392157
prohibición_terapias           5.392157
matrimonio_igualitario         5.392157
uniones_civiles                5.392157
adopción_conjunta              5.392157
adopción_segundo_progenitor    5.392157
dtype: float64

In [63]:
df_unido2.shape

(204, 15)

In [64]:
df_unido2.columns

Index(['país', 'índice de igualdad legal', 'legalidad_colectivo_lgbtiq+',
       'fecha_despenalización', 'pena_máxima', 'constitución',
       'protección_amplia', 'empleo', 'crimen_odio', 'incitación',
       'prohibición_terapias', 'matrimonio_igualitario', 'uniones_civiles',
       'adopción_conjunta', 'adopción_segundo_progenitor'],
      dtype='object')

In [65]:
df_unido2[df_unido2["índice de igualdad legal"].isnull()]

,país,índice de igualdad legal,legalidad_colectivo_lgbtiq+,fecha_despenalización,pena_máxima,constitución,protección_amplia,empleo,crimen_odio,incitación,prohibición_terapias,matrimonio_igualitario,uniones_civiles,adopción_conjunta,adopción_segundo_progenitor
28,Bosnia & Herzegovina,NaN,Si,2003,Desconocido,No,Si,Si,Si,Limitada,No,No,No,No,No
35,Brunei Darussalam,NaN,No,0,10 años,No,No,No,No,No,No,No,No,No,No
39,Cabo Verde,NaN,Si,2004,Desconocido,No,No,Si,Si,No,No,No,No,No,No
60,Czech Republic,NaN,Si,1962,Desconocido,No,Si,Si,No,No,No,No,Si,No,No
62,Côte d'Ivoire,NaN,Si,0000,Desconocido,No,No,No,No,No,No,No,No,No,No
123,Kosovo,NaN,Si,1994,Desconocido,No,Si,Si,Si,Si,No,No,No,No,No
148,Micronesia,NaN,Si,0000,Desconocido,No,Si,Si,No,No,No,No,No,No,No
177,Palestine,NaN,Si,1951,Desconocido,No,No,No,No,No,No,No,No,No,No
194,Saint Kitts & Nevis,NaN,No,0,10 años,No,No,No,Limitada,No,No,No,No,No,No
199,Saint Vinc. & the Gren.,NaN,No,0,10 años,No,No,No,Limitada,No,No,No,No,No,No
203,Sao Tome & Principe,NaN,Si,2012,Desconocido,No,No,Si,Si,No,No,No,No,No,No
253,Vatican City,NaN,Si,1890,Desconocido,No,No,No,No,No,No,No,No,No,No

PARA LAS SIGUIENTES COLUMNAS, QUE SON LAS QUE TIENEN NULOS, COMO NO HAY CATEGORIA DOMINANTE, LOS REEMPLAZAMOS POR "Unknown"
índice de igualdad legal      
legalidad_colectivo_lgbtiq+    
fecha_despenalización         
constitución                 
protección_amplia              
empleo                      
crimen_odio                  
incitación                    
prohibición_terapias          
matrimonio_igualitario       
uniones_civiles                
adopción_conjunta              
adopción_segundo_progenitor

In [66]:
# GESTIONAMOS LOS NULOS

columnas_unknown = ["índice de igualdad legal", "legalidad_colectivo_lgbtiq+", 'fecha_despenalización', 'constitución', 'protección_amplia', 'empleo', 'crimen_odio', 'incitación', 'prohibición_terapias', 'matrimonio_igualitario', 'uniones_civiles', 'adopción_conjunta', 'adopción_segundo_progenitor']   

# iteramos por la lista de columnas a las que le vamos a cambiar los nulos por "Uknown"
for columna in columnas_unknown:
    
    # reemplazamos los nulos por el valor Unknown para cada una de las columnas de la lista
    df_unido2[columna] = df_unido2[columna].fillna("Unknown")

print("Después del reemplazo usando 'fillna' quedan los siguientes nulos")
df_unido2[columnas_unknown].isnull().sum()

Después del reemplazo usando 'fillna' quedan los siguientes nulos

/var/folders/_8/rv04zc812vngdv98w27kqfbw0000gp/T/ipykernel_7659/842583585.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unido2[columna] = df_unido2[columna].fillna("Unknown")

índice de igualdad legal       0
legalidad_colectivo_lgbtiq+    0
fecha_despenalización          0
constitución                   0
protección_amplia              0
empleo                         0
crimen_odio                    0
incitación                     0
prohibición_terapias           0
matrimonio_igualitario         0
uniones_civiles                0
adopción_conjunta              0
adopción_segundo_progenitor    0
dtype: int64

In [67]:
df_unido2[df_unido2['fecha_despenalización'] == 'Unknown']['país']

29               Bosnia and Herzegovina
34                               Brunei
46             Central African Republic
55                        Cote d'Ivoire
61                              Czechia
64         Democratic Republic of Congo
108                           Indonesia
111                                Iraq
195               Saint Kitts and Nevis
200    Saint Vincent and the Grenadines
204               Sao Tome and Principe
230                              Taiwan
Name: país, dtype: object

In [68]:
# PARA PODER PASAR LA COLUMNA A INT, LE PEDÍ A CHAT QUE ME DIJERA LA INFO DE LOS PAISES FALTANTES, PORQ NO ME DEJABA CON 'Unknown'
despenalizacion = {
    'Bosnia and Herzegovina': 1998,
    'Brunei': 2007,  
    'Central African Republic': 1996,
    'Cote d\'Ivoire': 2016,
    'Czechia': 1962,
    'Democratic Republic of Congo': 0,  # Este país sigue teniendo la homosexualidad ilegal
    'Indonesia': 0,  # La homosexualidad no está penalizada a nivel nacional, pero depende de la región
    'Iraq': 0,  # Homosexualidad sigue siendo ilegal en Iraq
    'Saint Kitts and Nevis': 1998,
    'Saint Vincent and the Grenadines': 2001,
    'Sao Tome and Principe': 2012,
    'Taiwan': 1997
}

# Reemplazar los valores 'Unknown' en 'fecha_despenalización' con los años del diccionario
for pais, ano in despenalizacion.items():
    df_unido2.loc[(df_unido2['país'] == pais) & (df_unido2['fecha_despenalización'] == 'Unknown'), 'fecha_despenalización'] = ano

In [69]:
# Vemos los países que tienen Unknown en la columna "índice de igualdad legal"
df_unido2[df_unido2['índice de igualdad legal'] == 'Unknown']['país']

28        Bosnia & Herzegovina
35           Brunei Darussalam
39                  Cabo Verde
60              Czech Republic
62               Côte d'Ivoire
123                     Kosovo
148                 Micronesia
177                  Palestine
194        Saint Kitts & Nevis
199    Saint Vinc. & the Gren.
203        Sao Tome & Principe
253               Vatican City
Name: país, dtype: object

In [70]:
# PARA PODER PASAR LA COLUMNA A FLOAT, LE PEDÍ A CHAT QUE ME DIJERA LA INFO DE LOS PAISES FALTANTES, PORQ NO ME DEJABA CON 'Unknown'
indice = {
    'Bosnia & Herzegovina': 30,
    'Brunei Darussalam': 0,
    'Cabo Verde': 50,
    'Czech Republic': 80,
    'Côte d\'Ivoire': 50,
    'Kosovo': 40,
    'Micronesia': 60,
    'Palestine': 10,
    'Saint Kitts & Nevis': 10,
    'Saint Vinc. & the Gren.': 20,
    'Sao Tome & Principe': 60,
    'Vatican City': 0}


# Reemplazar los valores 'Unknown' en 'índice de igualdad legal' con los años del diccionario
for pais, ind in indice.items():
    df_unido2.loc[(df_unido2['país'] == pais) & (df_unido2['índice de igualdad legal'] == 'Unknown'), 'índice de igualdad legal'] = ind

In [71]:
# Cambiamos el tipo de datos de la columna "índice de igualdad legal"
df_unido2['índice de igualdad legal'] = df_unido2['índice de igualdad legal'].astype(float)

/var/folders/_8/rv04zc812vngdv98w27kqfbw0000gp/T/ipykernel_7659/2974434867.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unido2['índice de igualdad legal'] = df_unido2['índice de igualdad legal'].astype(float)

In [72]:
# Cambiamos el tipo de datos de la columna "año_actualización_datos"
df_unido2['fecha_despenalización'] = df_unido2['fecha_despenalización'].astype(int)

/var/folders/_8/rv04zc812vngdv98w27kqfbw0000gp/T/ipykernel_7659/3098850872.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unido2['fecha_despenalización'] = df_unido2['fecha_despenalización'].astype(int)

In [73]:
df_unido2.dtypes

país                            object
índice de igualdad legal       float64
legalidad_colectivo_lgbtiq+     object
fecha_despenalización            int64
pena_máxima                     object
constitución                    object
protección_amplia               object
empleo                          object
crimen_odio                     object
incitación                      object
prohibición_terapias            object
matrimonio_igualitario          object
uniones_civiles                 object
adopción_conjunta               object
adopción_segundo_progenitor     object
dtype: object

In [74]:
df_unido2.head(10)

,país,índice de igualdad legal,legalidad_colectivo_lgbtiq+,fecha_despenalización,pena_máxima,constitución,protección_amplia,empleo,crimen_odio,incitación,prohibición_terapias,matrimonio_igualitario,uniones_civiles,adopción_conjunta,adopción_segundo_progenitor
0,Afghanistan,0.00,No,0,Pena de muerte,No,No,No,No,No,No,No,No,No,No
2,Albania,62.27,Si,1995,Desconocido,No,Si,Si,Si,Si,No,No,No,No,No
3,Algeria,3.42,No,0,2 años,No,No,No,No,No,No,No,No,No,No
5,Andorra,85.71,Si,1990,Desconocido,No,Si,Si,Si,No,No,No,Si,Si,Si
6,Angola,66.19,Si,2021,Desconocido,No,Si,Si,Si,Si,No,No,No,No,No
8,Antigua and Barbuda,84.21,No,0,15 años,No,No,No,Limitada,No,No,No,No,No,No
9,Argentina,87.17,Si,1903,Desconocido,No,Limitada,Limitada,Si,No,Limitada,Si,Si,Si,Si
10,Armenia,47.73,Si,2003,Desconocido,No,No,No,No,No,No,No,No,No,No
13,Australia,89.65,Si,1997,Desconocido,No,Si,Si,Limitada,Si,Limitada,Si,Si,Si,Si
14,Austria,92.96,Si,1971,Desconocido,No,Si,Si,Si,Si,No,Si,Si,Si,Si

In [75]:
df_unido2.to_csv('LegalidadLGTBIQA+.csv')