In [1]:
# Import necessary libraries
import pandas as pd        # For data manipulation and analysis
import numpy as np         # For numerical operations
import requests            # To make HTTP requests (e.g., APIs)
import warnings            # To manage warning messages

# Set pandas to display all columns when showing DataFrames
pd.set_option('display.max_columns', None)

In [2]:
## DF OMOPHOBIA: 
## Fuente:

In [3]:
df_omophobia = pd.read_csv('files/omophobia.csv', encoding="latin1", delimiter=";")
df_omophobia.head(10)

,COUNTRY,CSSSA LEGAL?,DATE OF DECRIM,MAX PENALTY,CONST.,BROAD PROT.,EMPLOY.,HATE CRIME,INCITEMENT,BAN CONV. THERAPIES,SAME SEX MARRIAGE,CIVIL UNIONS,JOINT ADOPTION,SECOND PARENT ADOPTION
0,Algeria,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
1,Angola,YES,2021,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO
2,Benin,YES,NEVER CRIM,-,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
3,Botswana,YES,2019,-,NO,NO,YES,NO,NO,NO,NO,NO,NO,NO
4,Burkina Faso,YES,NEVER CRIM,-,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
5,Burundi,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
6,Cameroon,NO,-,5,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
7,Cabo Verde,YES,2004,-,NO,NO,YES,YES,NO,NO,NO,NO,NO,NO
8,Central Africa Republic,YES,NEVER CRIM,-,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
9,Chad,NO,-,2,NO,NO,NO,YES,NO,NO,NO,NO,NO,NO

In [4]:
df_omophobia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   COUNTRY                 241 non-null    object
 1   CSSSA LEGAL?            241 non-null    object
 2   DATE OF DECRIM          240 non-null    object
 3   MAX PENALTY             241 non-null    object
 4   CONST.                  197 non-null    object
 5   BROAD PROT.             241 non-null    object
 6   EMPLOY.                 241 non-null    object
 7   HATE CRIME              241 non-null    object
 8   INCITEMENT              241 non-null    object
 9   BAN CONV. THERAPIES     241 non-null    object
 10  SAME SEX MARRIAGE       241 non-null    object
 11  CIVIL UNIONS            241 non-null    object
 12  JOINT ADOPTION          241 non-null    object
 13  SECOND PARENT ADOPTION  241 non-null    object
dtypes: object(14)
memory usage: 26.5+ KB

In [5]:
## DF Criminalizacion
## Source: https://www.humandignitytrust.org/lgbt-the-law/map-of-criminalisation/

In [6]:
df_criminalization = pd.read_csv('files/Criminalizacion_LGBT.csv')
df_criminalization

,País,Criminaliza a personas LGBT,Criminaliza actividad sexual entre hombres,Criminaliza actividad sexual entre mujeres,Criminaliza la expresión de género de personas trans,Impone la pena de muerte,Pena máxima
0,Afganistán,Sí,Sí,Sí,No,Sí,Pena de muerte
1,Bangladés,Sí,Sí,Sí,No,No,Cadena perpetua
2,Brunéi,Sí,Sí,Sí,Sí,Sí,Muerte por lapidación
3,Indonesia,Sí,Sí,Sí,Sí,No,Ocho años de prisión y 100 latigazos
4,Irán,Sí,Sí,Sí,No,Sí,Pena de muerte
...,...,...,...,...,...,...,...
59,San Vicente y las Granadinas,Sí,Sí,Sí,NaN,NaN,Diez años de prisión
60,Trinidad y Tobago,Sí,Sí,Sí,NaN,NaN,Diez años de prisión
61,Belice,Sí,Sí,Sí,NaN,NaN,Diez años de prisión
62,Dominicana,Sí,Sí,Sí,NaN,NaN,NaN
63,Jordania,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_criminalization.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 7 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   País                                                  64 non-null     object
 1   Criminaliza a personas LGBT                           63 non-null     object
 2   Criminaliza actividad sexual entre hombres            63 non-null     object
 3   Criminaliza actividad sexual entre mujeres            63 non-null     object
 4   Criminaliza la expresión de género de personas trans  59 non-null     object
 5   Impone la pena de muerte                              59 non-null     object
 6   Pena máxima                                           62 non-null     object
dtypes: object(7)
memory usage: 3.6+ KB

In [8]:
## DF Index
## Source: https://ourworldindata.org/grapher/lgbt-legal-equality-index

In [9]:
df_index = pd.read_csv('files/lgbt-legal-equality-index.csv')
df_index

          Entity      Code  Year   ei_legal
0    Afghanistan       AFG  2024   0.000000
1         Africa       NaN  2024  20.723385
2        Albania       ALB  2024  62.270000
3        Algeria       DZA  2024   3.420000
4        Andorra       AND  2024  85.710000
..           ...       ...   ...        ...
196      Vietnam       VNM  2024  58.180000
197        World  OWID_WRL  2024  49.721184
198        Yemen       YEM  2024   0.000000
199       Zambia       ZMB  2024  17.650000
200     Zimbabwe       ZWE  2024  33.030000

[201 rows x 4 columns]

In [10]:
df_index['Entity'].unique()

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Asia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
       'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus',
       'Czechia', 'Democratic Republic of Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Europe', 'Fiji', 'Finland', 'France',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (country)', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'North America', 'North Korea',
       'North Macedonia', 'Norway', 'Oceania', 'Oman', 'Pakistan',
       'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia',
       'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South America',
       'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
       'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Venezuela', 'Vietnam', 'World', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [11]:
df_omophobia.columns

Index(['COUNTRY', 'CSSSA LEGAL?', 'DATE OF DECRIM', 'MAX PENALTY', 'CONST.',
       'BROAD PROT.', 'EMPLOY.', 'HATE CRIME', 'INCITEMENT',
       'BAN CONV. THERAPIES', 'SAME SEX MARRIAGE', 'CIVIL UNIONS',
       'JOINT ADOPTION', 'SECOND PARENT ADOPTION'],
      dtype='object')

In [12]:

df_index.rename(columns={"Entity": 'COUNTRY'}, inplace=True)

In [13]:
df_index

         COUNTRY      Code  Year   ei_legal
0    Afghanistan       AFG  2024   0.000000
1         Africa       NaN  2024  20.723385
2        Albania       ALB  2024  62.270000
3        Algeria       DZA  2024   3.420000
4        Andorra       AND  2024  85.710000
..           ...       ...   ...        ...
196      Vietnam       VNM  2024  58.180000
197        World  OWID_WRL  2024  49.721184
198        Yemen       YEM  2024   0.000000
199       Zambia       ZMB  2024  17.650000
200     Zimbabwe       ZWE  2024  33.030000

[201 rows x 4 columns]

In [14]:
# Merge df_index and df_omophobia using an outer join on the 'COUNTRY' column
# This keeps all rows from both DataFrames and adds a column to indicate the source
df_merged = pd.merge(df_index, df_omophobia, on='COUNTRY', how='outer', indicator=True)

# Filter to see countries that exist only in df_index
only_in_df_index = df_merged[df_merged['_merge'] == 'left_only']

# Filter to see countries that exist only in df_omophobia
only_in_df_omophobia = df_merged[df_merged['_merge'] == 'right_only']

# Filter to see countries that are present in both DataFrames
countries_in_both = df_merged[df_merged['_merge'] == 'both']

In [15]:
countries_in_both

,COUNTRY,Code,Year,ei_legal,CSSSA LEGAL?,DATE OF DECRIM,MAX PENALTY,CONST.,BROAD PROT.,EMPLOY.,HATE CRIME,INCITEMENT,BAN CONV. THERAPIES,SAME SEX MARRIAGE,CIVIL UNIONS,JOINT ADOPTION,SECOND PARENT ADOPTION,_merge
0,Afghanistan,AFG,2024.0,0.00,NO,-,DEATH (P),NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
2,Albania,ALB,2024.0,62.27,YES,1995,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO,both
3,Algeria,DZA,2024.0,3.42,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
5,Andorra,AND,2024.0,85.71,YES,1990,-,NO,YES,YES,YES,NO,NO,NO,YES,YES,YES,both
6,Angola,AGO,2024.0,66.19,YES,2021,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,Venezuela,VEN,2024.0,51.82,YES,1836,-,NO,NO,YES,NO,NO,NO,NO,NO,NO,NO,both
255,Vietnam,VNM,2024.0,58.18,YES,NEVER CRIM,-,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
258,Yemen,YEM,2024.0,0.00,NO,-,DEATH,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
259,Zambia,ZMB,2024.0,17.65,NO,-,FOR LIFE,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
260,Zimbabwe,ZWE,2024.0,33.03,NO,-,1,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both

In [16]:
only_in_df_omophobia.head()

,COUNTRY,Code,Year,ei_legal,CSSSA LEGAL?,DATE OF DECRIM,MAX PENALTY,CONST.,BROAD PROT.,EMPLOY.,HATE CRIME,INCITEMENT,BAN CONV. THERAPIES,SAME SEX MARRIAGE,CIVIL UNIONS,JOINT ADOPTION,SECOND PARENT ADOPTION,_merge
4,American Samoa (USA),NaN,NaN,NaN,YES,1980,-,NaN,NO,NO,NO,NO,NO,NO,NO,NO,NO,right_only
7,Anguilla (UK),NaN,NaN,NaN,YES,2001,-,NaN,NO,NO,LIMITED,NO,NO,NO,NO,NO,NO,right_only
11,Aruba (NL),NaN,NaN,NaN,YES,1869,-,NaN,YES,YES,NO,YES,NO,NO,YES,NO,NO,right_only
24,Bermuda (UK),NaN,NaN,NaN,YES,1994,-,NaN,YES,YES,YES,YES,NO,NO,NO,YES,YES,right_only
27,Bonaire (NL),NaN,NaN,NaN,YES,1869,-,NaN,YES,YES,NO,YES,NO,YES,YES,NO,NO,right_only

In [18]:
only_in_df_omophobia.head(5)

,COUNTRY,Code,Year,ei_legal,CSSSA LEGAL?,DATE OF DECRIM,MAX PENALTY,CONST.,BROAD PROT.,EMPLOY.,HATE CRIME,INCITEMENT,BAN CONV. THERAPIES,SAME SEX MARRIAGE,CIVIL UNIONS,JOINT ADOPTION,SECOND PARENT ADOPTION,_merge
4,American Samoa (USA),NaN,NaN,NaN,YES,1980,-,NaN,NO,NO,NO,NO,NO,NO,NO,NO,NO,right_only
7,Anguilla (UK),NaN,NaN,NaN,YES,2001,-,NaN,NO,NO,LIMITED,NO,NO,NO,NO,NO,NO,right_only
11,Aruba (NL),NaN,NaN,NaN,YES,1869,-,NaN,YES,YES,NO,YES,NO,NO,YES,NO,NO,right_only
24,Bermuda (UK),NaN,NaN,NaN,YES,1994,-,NaN,YES,YES,YES,YES,NO,NO,NO,YES,YES,right_only
27,Bonaire (NL),NaN,NaN,NaN,YES,1869,-,NaN,YES,YES,NO,YES,NO,YES,YES,NO,NO,right_only

In [19]:
df_merged

,COUNTRY,Code,Year,ei_legal,CSSSA LEGAL?,DATE OF DECRIM,MAX PENALTY,CONST.,BROAD PROT.,EMPLOY.,HATE CRIME,INCITEMENT,BAN CONV. THERAPIES,SAME SEX MARRIAGE,CIVIL UNIONS,JOINT ADOPTION,SECOND PARENT ADOPTION,_merge
0,Afghanistan,AFG,2024.0,0.000000,NO,-,DEATH (P),NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
1,Africa,NaN,2024.0,20.723385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,Albania,ALB,2024.0,62.270000,YES,1995,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO,both
3,Algeria,DZA,2024.0,3.420000,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
4,American Samoa (USA),NaN,NaN,NaN,YES,1980,-,NaN,NO,NO,NO,NO,NO,NO,NO,NO,NO,right_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,Wallis and Futuna (FR),NaN,NaN,NaN,YES,NEVER CRIM,-,NaN,YES,YES,YES,YES,NO,YES,YES,YES,YES,right_only
257,World,OWID_WRL,2024.0,49.721184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
258,Yemen,YEM,2024.0,0.000000,NO,-,DEATH,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
259,Zambia,ZMB,2024.0,17.650000,NO,-,FOR LIFE,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
260,Zimbabwe,ZWE,2024.0,33.030000,NO,-,1,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both

In [20]:
df_merged.columns

Index(['COUNTRY', 'Code', 'Year', 'ei_legal', 'CSSSA LEGAL?', 'DATE OF DECRIM',
       'MAX PENALTY', 'CONST.', 'BROAD PROT.', 'EMPLOY.', 'HATE CRIME',
       'INCITEMENT', 'BAN CONV. THERAPIES', 'SAME SEX MARRIAGE',
       'CIVIL UNIONS', 'JOINT ADOPTION', 'SECOND PARENT ADOPTION', '_merge'],
      dtype='object')

In [21]:
# Remove columns 'Code' & 'Merge'
df_merged.drop(columns=['Code', '_merge'], inplace=True)

In [22]:
# Save changes
df_merged.rename(columns=lambda x: x.lower(), inplace=True)

In [23]:
df_merged.head()

,country,year,ei_legal,csssa legal?,date of decrim,max penalty,const.,broad prot.,employ.,hate crime,incitement,ban conv. therapies,same sex marriage,civil unions,joint adoption,second parent adoption
0,Afghanistan,2024.0,0.000000,NO,-,DEATH (P),NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
1,Africa,2024.0,20.723385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,2024.0,62.270000,YES,1995,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO
3,Algeria,2024.0,3.420000,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
4,American Samoa (USA),NaN,NaN,YES,1980,-,NaN,NO,NO,NO,NO,NO,NO,NO,NO,NO

In [24]:
df_merged.dtypes

country                    object
year                      float64
ei_legal                  float64
csssa legal?               object
date of decrim             object
max penalty                object
const.                     object
broad prot.                object
employ.                    object
hate crime                 object
incitement                 object
ban conv. therapies        object
same sex marriage          object
civil unions               object
joint adoption             object
second parent adoption     object
dtype: object

In [25]:
df_merged.isnull().mean() * 100

country                    0.000000
year                      22.988506
ei_legal                  22.988506
csssa legal?               7.662835
date of decrim             8.045977
max penalty                7.662835
const.                    24.521073
broad prot.                7.662835
employ.                    7.662835
hate crime                 7.662835
incitement                 7.662835
ban conv. therapies        7.662835
same sex marriage          7.662835
civil unions               7.662835
joint adoption             7.662835
second parent adoption     7.662835
dtype: float64

In [26]:
# Define the original column names to keep from the merged DataFrame
columns_originales = [
    'country', 'year', 'ei_legal', 'csssa legal?', 'date of decrim',
    'max penalty', 'const.', 'broad prot.', 'employ.', 'hate crime',
    'incitement', 'ban conv. therapies', 'same sex marriage',
    'civil unions', 'joint adoption', 'second parent adoption'
]

# Rebuild the DataFrame with only the selected columns
df_merged = pd.DataFrame(df_merged, columns=columns_originales)

# Define the new (translated/renamed) column names in Spanish
nuevos_nombres = [
    'país', 'año_actualización_datos', 'índice de igualdad legal', 'legalidad_colectivo_lgbtiq+', 'fecha_despenalización',
    'pena_máxima', 'constitución', 'protección_amplia', 'empleo', 'crimen_odio',
    'incitación', 'prohibición_terapias', 'matrimonio_igualitario',
    'uniones_civiles', 'adopción_conjunta', 'adopción_segundo_progenitor'
]

# Apply the new column names to the DataFrame
df_merged.columns = nuevos_nombres

In [27]:
df_merged.head()

,país,año_actualización_datos,índice de igualdad legal,legalidad_colectivo_lgbtiq+,fecha_despenalización,pena_máxima,constitución,protección_amplia,empleo,crimen_odio,incitación,prohibición_terapias,matrimonio_igualitario,uniones_civiles,adopción_conjunta,adopción_segundo_progenitor
0,Afghanistan,2024.0,0.000000,NO,-,DEATH (P),NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
1,Africa,2024.0,20.723385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,2024.0,62.270000,YES,1995,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO
3,Algeria,2024.0,3.420000,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
4,American Samoa (USA),NaN,NaN,YES,1980,-,NaN,NO,NO,NO,NO,NO,NO,NO,NO,NO

In [28]:
df_merged.shape

(261, 16)

In [31]:
# Quitamos los que no eran países

no_paises = [
    "Africa",
    "American Samoa (USA)",
    "Anguilla (UK)",
    "Aruba (NL)",
    "Asia",
    "Bermuda (UK)",
    "Bonaire (NL)",
    "British Indian Terr. (UK)",
    "British Virgin Islands (UK)",
    "Cape Verde",  # (duplicado de Cabo Verde)
    "Cayman Islands (UK)",
    "Central Africa Republic",
    "Cook Islands (NZ)",
    "Curacao (NL)",
    "DRC",  # (abreviatura de Democratic Republic of Congo)
    "Europe",
    "Falkland/Malv. (UK/AR)",
    "Faroe Islands (DN)",
    "French Guiana (FR)",
    "French Polynesia (FR)",
    "Gibraltar (UK)",
    "Greenland (DN)",
    "Guadeloupe (FR)",
    "Guam (USA)",
    "Guernsey (UK)",
    "Hong Kong (SAR China)",
    "Indonesia1",  # (error tipográfico de Indonesia)
    "Isle of Man (UK)",
    "Jersey (UK)",
    "Macau (China)",
    "Martinique (FR)",
    "Mayotte (FR)",
    "Micronesia (country)",  # (duplicado de Micronesia)
    "Montserrat (UK)",
    "New Caledonia (FR)",
    "Niue (NZ)",
    "North America",
    "Oceania",
    "Pitcairn Islands (UK)",
    "North. Mariana Is. (USA)",
    "Puerto Rico (USA)",
    "Reunion (FR)",
    "Saba (NL)",
    "Saint Barthelemy (FR)",
    "Saint Martin (FR)",
    "Saint Pierre et Miq. (FR)",
    "Sint Eustatius (NL)",
    "Sint Maarten (NL)",
    "South America",
    "South Georg. & Sand. (UK)",
    "St. Helena, Asc., TdA (UK)",
    "Taiwan (China)",  # (duplicado de Taiwan)
    "Tokelau (NZ)",
    "Turks and Caicos (UK)",
    "US Virgin Islands (USA)",
    "Wallis and Futuna (FR)",
    "World"
]

df_merged_2 = df_merged[~df_merged['país'].isin(no_paises)]

In [32]:
df_merged_2.shape

(204, 16)

In [33]:
# Check unique values from 'Año_actualización_datos'
df_merged['año_actualización_datos'].unique()

array([2024.,   nan])

In [34]:
# Get the mode (most frequent value) of the column to use for filling missing values
moda = df_merged_2["año_actualización_datos"].mode()[0]

In [35]:
# Reeplace nulls with the mode 
df_merged_2["año_actualización_datos"] = df_merged_2["año_actualización_datos"].fillna(moda)

/tmp/ipykernel_17821/3613578485.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_2["año_actualización_datos"] = df_merged_2["año_actualización_datos"].fillna(moda)

In [36]:
df_merged_2["año_actualización_datos"].isnull().sum()

0

In [37]:
df_merged_2['país'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia & Herzegovina', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Czechia',
       "Côte d'Ivoire", 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'East Timor',
       'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro',
       'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'North Korea', 'North Macedonia', 'Norway', 'Oman', 'Pakistan',
       'Palau', 'Palestine2', 'Panama', 'Papua New Guinea', 'Paraguay',
       'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania',
       'Russia', 'Rwanda', 'Saint Kitts & Nevis', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vinc. & the Gren.',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome & Principe', 'Sao Tome and Principe', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
       'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka',
       'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam', 'Yemen',
       'Zambia', 'Zimbabwe'], dtype=object)

In [38]:
# Correct 'Palestine' name
df_merged_2['país'] = df_merged_2['país'].replace('Palestine2', 'Palestine')

/tmp/ipykernel_17821/138012117.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_2['país'] = df_merged_2['país'].replace('Palestine2', 'Palestine')

In [39]:
df_merged_2['país'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia & Herzegovina', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Czechia',
       "Côte d'Ivoire", 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'East Timor',
       'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro',
       'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'North Korea', 'North Macedonia', 'Norway', 'Oman', 'Pakistan',
       'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay',
       'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania',
       'Russia', 'Rwanda', 'Saint Kitts & Nevis', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vinc. & the Gren.',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome & Principe', 'Sao Tome and Principe', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
       'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka',
       'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam', 'Yemen',
       'Zambia', 'Zimbabwe'], dtype=object)

In [40]:
df_merged_2.isnull().mean() * 100

país                           0.000000
año_actualización_datos        0.000000
índice de igualdad legal       5.882353
legalidad_colectivo_lgbtiq+    5.392157
fecha_despenalización          5.882353
pena_máxima                    5.392157
constitución                   5.392157
protección_amplia              5.392157
empleo                         5.392157
crimen_odio                    5.392157
incitación                     5.392157
prohibición_terapias           5.392157
matrimonio_igualitario         5.392157
uniones_civiles                5.392157
adopción_conjunta              5.392157
adopción_segundo_progenitor    5.392157
dtype: float64

In [41]:
df_merged_2.dtypes

país                            object
año_actualización_datos        float64
índice de igualdad legal       float64
legalidad_colectivo_lgbtiq+     object
fecha_despenalización           object
pena_máxima                     object
constitución                    object
protección_amplia               object
empleo                          object
crimen_odio                     object
incitación                      object
prohibición_terapias            object
matrimonio_igualitario          object
uniones_civiles                 object
adopción_conjunta               object
adopción_segundo_progenitor     object
dtype: object

In [42]:
# Change the data type of the "año_actualización_datos" column to integer
df_merged_2['año_actualización_datos'] = df_merged_2['año_actualización_datos'].astype(int)

/tmp/ipykernel_17821/2708002676.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_2['año_actualización_datos'] = df_merged_2['año_actualización_datos'].astype(int)

In [43]:
df_merged_2.dtypes

país                            object
año_actualización_datos          int64
índice de igualdad legal       float64
legalidad_colectivo_lgbtiq+     object
fecha_despenalización           object
pena_máxima                     object
constitución                    object
protección_amplia               object
empleo                          object
crimen_odio                     object
incitación                      object
prohibición_terapias            object
matrimonio_igualitario          object
uniones_civiles                 object
adopción_conjunta               object
adopción_segundo_progenitor     object
dtype: object

In [44]:
df_merged_2.head()

,país,año_actualización_datos,índice de igualdad legal,legalidad_colectivo_lgbtiq+,fecha_despenalización,pena_máxima,constitución,protección_amplia,empleo,crimen_odio,incitación,prohibición_terapias,matrimonio_igualitario,uniones_civiles,adopción_conjunta,adopción_segundo_progenitor
0,Afghanistan,2024,0.00,NO,-,DEATH (P),NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
2,Albania,2024,62.27,YES,1995,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO
3,Algeria,2024,3.42,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
5,Andorra,2024,85.71,YES,1990,-,NO,YES,YES,YES,NO,NO,NO,YES,YES,YES
6,Angola,2024,66.19,YES,2021,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO

In [45]:
df_merged_2['pena_máxima'].unique()

array(['DEATH (P)', '-', '2', '15', '10', 'FOR LIFE', '1', nan, '5',
       'UNDETERM.', '7', '3', '14', 'DEATH', '20', '8', 'VARIES'],
      dtype=object)

In [46]:
# Dictionary to map specific values to clearer, translated labels
replacements = {
    'DEATH': 'Pena de muerte',
    'DEATH (P)': 'Pena de muerte',
    '-': 'Desconocido',
    np.nan: 'Desconocido',  # np.nan can also be replaced using .replace
    'FOR LIFE': 'Cadena perpetua',
    'VARIES': 'Varía',
    'UNDETERM.': 'Indeterminado'
}

# Replace specific values in the 'pena_máxima' column using the dictionary
df_merged_2['pena_máxima'] = df_merged_2['pena_máxima'].replace(replacements)

# If the value is numeric, append "años" (years); otherwise, leave it as-is
df_merged_2['pena_máxima'] = df_merged_2['pena_máxima'].apply(lambda x: f"{x} años" if str(x).isdigit() else x)

/tmp/ipykernel_17821/2817930550.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_2['pena_máxima'] = df_merged_2['pena_máxima'].replace(replacements)
/tmp/ipykernel_17821/2817930550.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_2['pena_máxima'] = df_merged_2['pena_máxima'].apply(lambda x: f"{x} años" if str(x).isdigit() else x)

In [47]:
df_merged_2['pena_máxima'].unique()

array(['Pena de muerte', 'Desconocido', '2 años', '15 años', '10 años',
       'Cadena perpetua', '1 años', '5 años', 'Indeterminado', '7 años',
       '3 años', '14 años', '20 años', '8 años', 'Varía'], dtype=object)

In [48]:
# Standardize values across the dataset to make them consistent

# Dictionary to replace English responses with Spanish equivalents
replacements1 = {
    'YES': 'Si',
    'NO': 'No',
    'LIMITED': 'Limitada'
}

# List of columns where replacements should be applied
columns_to_modify = [
    "legalidad_colectivo_lgbtiq+", "fecha_despenalización", "constitución",
    "protección_amplia", "empleo", "crimen_odio", "incitación",
    "prohibición_terapias", "matrimonio_igualitario", "uniones_civiles",
    "adopción_conjunta", "adopción_segundo_progenitor"
]

# Apply replacements to the specified columns
df_merged_2[columns_to_modify] = df_merged_2[columns_to_modify].replace(replacements1)

/tmp/ipykernel_17821/80582130.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_2[columns_to_modify] = df_merged_2[columns_to_modify].replace(replacements1)

In [49]:
df_merged_2.head()

,país,año_actualización_datos,índice de igualdad legal,legalidad_colectivo_lgbtiq+,fecha_despenalización,pena_máxima,constitución,protección_amplia,empleo,crimen_odio,incitación,prohibición_terapias,matrimonio_igualitario,uniones_civiles,adopción_conjunta,adopción_segundo_progenitor
0,Afghanistan,2024,0.00,No,-,Pena de muerte,No,No,No,No,No,No,No,No,No,No
2,Albania,2024,62.27,Si,1995,Desconocido,No,Si,Si,Si,Si,No,No,No,No,No
3,Algeria,2024,3.42,No,-,2 años,No,No,No,No,No,No,No,No,No,No
5,Andorra,2024,85.71,Si,1990,Desconocido,No,Si,Si,Si,No,No,No,Si,Si,Si
6,Angola,2024,66.19,Si,2021,Desconocido,No,Si,Si,Si,Si,No,No,No,No,No

In [50]:
# Remove the column 'año_actualización_datos' since all are from 2024
df_merged_2.drop(columns=['año_actualización_datos'], inplace=True)
# Save changes
df_merged_2.rename(columns=lambda x: x.lower(), inplace=True)

/tmp/ipykernel_17821/2785310845.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_2.drop(columns=['año_actualización_datos'], inplace=True)
/tmp/ipykernel_17821/2785310845.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_2.rename(columns=lambda x: x.lower(), inplace=True)

In [51]:
df_merged_2['fecha_despenalización'].unique()

array(['-', '1995', '1990', '2021', '1903', '2003', '1975-1997', '1971',
       '2000', '1991', '1976', '1994', '1795', '2016', 'NEVER CRIM',
       '1832', '1991-2003', nan, '2019', '1831', '1968', '2004', '1969',
       '1999', '1997', '1981', '1977', '1979', '1998', '1962', '1933',
       '1822', '1975', '1826', '1992', '2010', '1791', '2020',
       '1968-1969', '1951', '1834', '1993', '1899', '1940', '2018',
       '1988', '1890', '1882', '2012', '1989', '1973', '2005', '1872',
       '1793', '1961', '2015', '2007', '1811', '1986', '2008', '1996',
       '1972', '2014', '1924', '1870', '1932', '1983', '1869', '1944',
       '1942', '1957', '1858', '1967-1982', '1962-2003', '1934', '1836'],
      dtype=object)

In [52]:
df_merged_2[df_merged_2['fecha_despenalización'] == 'NEVER CRIM']

,país,índice de igualdad legal,legalidad_colectivo_lgbtiq+,fecha_despenalización,pena_máxima,constitución,protección_amplia,empleo,crimen_odio,incitación,prohibición_terapias,matrimonio_igualitario,uniones_civiles,adopción_conjunta,adopción_segundo_progenitor
23,Benin,43.81,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
37,Burkina Faso,52.22,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
40,Cambodia,53.89,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
52,Congo,43.81,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
62,Côte d'Ivoire,NaN,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
66,Djibouti,32.82,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
73,Equatorial Guinea,48.57,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
126,Laos,49.47,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
136,Madagascar,43.81,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
140,Mali,32.73,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
148,Micronesia,NaN,Si,NEVER CRIM,Desconocido,No,Si,Si,No,No,No,No,No,No,No
165,Niger,40.50,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
169,North Korea,38.33,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
191,Rwanda,45.00,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No
220,South Korea,48.33,Si,NEVER CRIM,Desconocido,No,Limitada,Limitada,No,No,No,No,No,No,No
252,Vanuatu,60.53,Si,NEVER CRIM,Desconocido,No,No,Limitada,No,No,No,No,No,No,No
255,Vietnam,58.18,Si,NEVER CRIM,Desconocido,No,No,No,No,No,No,No,No,No,No

In [53]:
# Search which countries have 'NEVER CRIM' in 'fecha_despenalización' column
df_merged_2[df_merged_2['fecha_despenalización'] == 'NEVER CRIM']['país']

23                 Benin
37          Burkina Faso
40              Cambodia
52                 Congo
62         Côte d'Ivoire
66              Djibouti
73     Equatorial Guinea
126                 Laos
136           Madagascar
140                 Mali
148           Micronesia
165                Niger
169          North Korea
191               Rwanda
220          South Korea
252              Vanuatu
255              Vietnam
Name: país, dtype: object

In [54]:
df_merged_2[df_merged_2['fecha_despenalización'] == '-']

,país,índice de igualdad legal,legalidad_colectivo_lgbtiq+,fecha_despenalización,pena_máxima,constitución,protección_amplia,empleo,crimen_odio,incitación,prohibición_terapias,matrimonio_igualitario,uniones_civiles,adopción_conjunta,adopción_segundo_progenitor
0,Afghanistan,0.00,No,-,Pena de muerte,No,No,No,No,No,No,No,No,No,No
3,Algeria,3.42,No,-,2 años,No,No,No,No,No,No,No,No,No,No
8,Antigua and Barbuda,84.21,No,-,15 años,No,No,No,Limitada,No,No,No,No,No,No
18,Bangladesh,23.25,No,-,10 años,No,No,No,No,No,No,No,No,No,No
19,Barbados,54.76,No,-,Cadena perpetua,No,No,Si,No,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,United Arab Emirates,4.88,No,-,Pena de muerte,No,No,No,No,No,No,No,No,No,No
251,Uzbekistan,20.83,No,-,3 años,No,No,No,No,No,No,No,No,No,No
258,Yemen,0.00,No,-,Pena de muerte,No,No,No,No,No,No,No,No,No,No
259,Zambia,17.65,No,-,Cadena perpetua,No,No,No,No,No,No,No,No,No,No
260,Zimbabwe,33.03,No,-,1 años,No,No,No,No,No,No,No,No,No,No

In [55]:
df_merged_2[df_merged_2['fecha_despenalización'] == '-']['país']

0               Afghanistan
3                   Algeria
8       Antigua and Barbuda
18               Bangladesh
19                 Barbados
               ...
247    United Arab Emirates
251              Uzbekistan
258                   Yemen
259                  Zambia
260                Zimbabwe
Name: país, Length: 68, dtype: object

In [56]:
# Modify unexisting dates (0 - '-')
df_merged_2['fecha_despenalización'] = df_merged_2['fecha_despenalización'].replace({
    '-': '0', 
    'NEVER CRIM': '0000', 
    '1975-1997': '1997', 
    '1991-2003': '2003',
    '1968-1969': '1969',
    '1967-1982': '1982',
    '1962-2003': '2003'
})

/tmp/ipykernel_17821/391955565.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_2['fecha_despenalización'] = df_merged_2['fecha_despenalización'].replace({

In [57]:
df_merged_2['fecha_despenalización'].unique()

array(['0', '1995', '1990', '2021', '1903', '2003', '1997', '1971',
       '2000', '1991', '1976', '1994', '1795', '2016', '0000', '1832',
       nan, '2019', '1831', '1968', '2004', '1969', '1999', '1981',
       '1977', '1979', '1998', '1962', '1933', '1822', '1975', '1826',
       '1992', '2010', '1791', '2020', '1951', '1834', '1993', '1899',
       '1940', '2018', '1988', '1890', '1882', '2012', '1989', '1973',
       '2005', '1872', '1793', '1961', '2015', '2007', '1811', '1986',
       '2008', '1996', '1972', '2014', '1924', '1870', '1932', '1983',
       '1869', '1944', '1942', '1957', '1858', '1982', '1934', '1836'],
      dtype=object)

In [58]:
df_merged_2.isnull().sum() / df_merged_2.shape[0] * 100

país                           0.000000
índice de igualdad legal       5.882353
legalidad_colectivo_lgbtiq+    5.392157
fecha_despenalización          5.882353
pena_máxima                    0.000000
constitución                   5.392157
protección_amplia              5.392157
empleo                         5.392157
crimen_odio                    5.392157
incitación                     5.392157
prohibición_terapias           5.392157
matrimonio_igualitario         5.392157
uniones_civiles                5.392157
adopción_conjunta              5.392157
adopción_segundo_progenitor    5.392157
dtype: float64

In [59]:
df_merged_2.shape

(204, 15)

In [60]:
df_merged_2.columns

Index(['país', 'índice de igualdad legal', 'legalidad_colectivo_lgbtiq+',
       'fecha_despenalización', 'pena_máxima', 'constitución',
       'protección_amplia', 'empleo', 'crimen_odio', 'incitación',
       'prohibición_terapias', 'matrimonio_igualitario', 'uniones_civiles',
       'adopción_conjunta', 'adopción_segundo_progenitor'],
      dtype='object')

In [61]:
df_merged_2[df_merged_2["índice de igualdad legal"].isnull()]

,país,índice de igualdad legal,legalidad_colectivo_lgbtiq+,fecha_despenalización,pena_máxima,constitución,protección_amplia,empleo,crimen_odio,incitación,prohibición_terapias,matrimonio_igualitario,uniones_civiles,adopción_conjunta,adopción_segundo_progenitor
28,Bosnia & Herzegovina,NaN,Si,2003,Desconocido,No,Si,Si,Si,Limitada,No,No,No,No,No
35,Brunei Darussalam,NaN,No,0,10 años,No,No,No,No,No,No,No,No,No,No
39,Cabo Verde,NaN,Si,2004,Desconocido,No,No,Si,Si,No,No,No,No,No,No
60,Czech Republic,NaN,Si,1962,Desconocido,No,Si,Si,No,No,No,No,Si,No,No
62,Côte d'Ivoire,NaN,Si,0000,Desconocido,No,No,No,No,No,No,No,No,No,No
123,Kosovo,NaN,Si,1994,Desconocido,No,Si,Si,Si,Si,No,No,No,No,No
148,Micronesia,NaN,Si,0000,Desconocido,No,Si,Si,No,No,No,No,No,No,No
177,Palestine,NaN,Si,1951,Desconocido,No,No,No,No,No,No,No,No,No,No
194,Saint Kitts & Nevis,NaN,No,0,10 años,No,No,No,Limitada,No,No,No,No,No,No
199,Saint Vinc. & the Gren.,NaN,No,0,10 años,No,No,No,Limitada,No,No,No,No,No,No
203,Sao Tome & Principe,NaN,Si,2012,Desconocido,No,No,Si,Si,No,No,No,No,No,No
253,Vatican City,NaN,Si,1890,Desconocido,No,No,No,No,No,No,No,No,No,No

# List of columns with missing values that should be filled with "Unknown"
columns_with_nulls = [
    "índice de igualdad legal", "legalidad_colectivo_lgbtiq+", "fecha_despenalización",
    "constitución", "protección_amplia", "empleo", "crimen_odio", "incitación",
    "prohibición_terapias", "matrimonio_igualitario", "uniones_civiles",
    "adopción_conjunta", "adopción_segundo_progenitor"
]

# Replace NaN values with "Unknown" in the selected columns
df_merged_2[columns_with_nulls] = df_merged_2[columns_with_nulls].fillna("Unknown")

In [62]:
# HANDLE MISSING VALUES

# List of columns where missing values will be replaced with "Unknown"
columns_unknown = [
    "índice de igualdad legal", "legalidad_colectivo_lgbtiq+", "fecha_despenalización",
    "constitución", "protección_amplia", "empleo", "crimen_odio", "incitación",
    "prohibición_terapias", "matrimonio_igualitario", "uniones_civiles",
    "adopción_conjunta", "adopción_segundo_progenitor"
]

# Iterate over the list of columns and replace missing values with "Unknown"
for column in columns_unknown:
    df_merged_2[column] = df_merged_2[column].fillna("Unknown")

# Display how many missing values remain in those columns after replacement
print("After using 'fillna', the following nulls remain:")
df_merged_2[columns_unknown].isnull().sum()

After using 'fillna', the following nulls remain:

/tmp/ipykernel_17821/2147163630.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_2[column] = df_merged_2[column].fillna("Unknown")

índice de igualdad legal       0
legalidad_colectivo_lgbtiq+    0
fecha_despenalización          0
constitución                   0
protección_amplia              0
empleo                         0
crimen_odio                    0
incitación                     0
prohibición_terapias           0
matrimonio_igualitario         0
uniones_civiles                0
adopción_conjunta              0
adopción_segundo_progenitor    0
dtype: int64

In [63]:
df_merged_2[df_merged_2['fecha_despenalización'] == 'Unknown']['país']

29               Bosnia and Herzegovina
34                               Brunei
46             Central African Republic
55                        Cote d'Ivoire
61                              Czechia
64         Democratic Republic of Congo
108                           Indonesia
111                                Iraq
195               Saint Kitts and Nevis
200    Saint Vincent and the Grenadines
204               Sao Tome and Principe
230                              Taiwan
Name: país, dtype: object

In [64]:
# To convert the column to integers, we needed to remove "Unknown" values
# This dictionary assigns decriminalization years to specific countries with missing data
decriminalization_years = {
    'Bosnia and Herzegovina': 1998,
    'Brunei': 2007,  
    'Central African Republic': 1996,
    "Cote d'Ivoire": 2016,
    'Czechia': 1962,
    'Democratic Republic of Congo': 0,  # Still criminalizes homosexuality
    'Indonesia': 0,  # Depends on region; not penalized nationwide
    'Iraq': 0,  # Homosexuality is still illegal
    'Saint Kitts and Nevis': 1998,
    'Saint Vincent and the Grenadines': 2001,
    'Sao Tome and Principe': 2012,
    'Taiwan': 1997
}

# Replace 'Unknown' values in 'fecha_despenalización' with the correct year from the dictionary
for country, year in decriminalization_years.items():
    df_merged_2.loc[
        (df_merged_2['país'] == country) & (df_merged_2['fecha_despenalización'] == 'Unknown'),
        'fecha_despenalización'
    ] = year

In [65]:
# Display the countries that have "Unknown" in the "índice de igualdad legal" column
df_merged_2[df_merged_2['índice de igualdad legal'] == 'Unknown']['país']

28        Bosnia & Herzegovina
35           Brunei Darussalam
39                  Cabo Verde
60              Czech Republic
62               Côte d'Ivoire
123                     Kosovo
148                 Micronesia
177                  Palestine
194        Saint Kitts & Nevis
199    Saint Vinc. & the Gren.
203        Sao Tome & Principe
253               Vatican City
Name: país, dtype: object

In [66]:
# To convert the column to float, we needed to remove "Unknown" values
# This dictionary provides the legal equality index values for countries with missing data
equality_index = {
    'Bosnia & Herzegovina': 30,
    'Brunei Darussalam': 0,
    'Cabo Verde': 50,
    'Czech Republic': 80,
    "Côte d'Ivoire": 50,
    'Kosovo': 40,
    'Micronesia': 60,
    'Palestine': 10,
    'Saint Kitts & Nevis': 10,
    'Saint Vinc. & the Gren.': 20,
    'Sao Tome & Principe': 60,
    'Vatican City': 0
}

# Replace 'Unknown' values in 'índice de igualdad legal' with the values from the dictionary
for country, index in equality_index.items():
    df_merged_2.loc[
        (df_merged_2['país'] == country) & (df_merged_2['índice de igualdad legal'] == 'Unknown'),
        'índice de igualdad legal'
    ] = index

In [67]:
# Convert the data type of the "índice de igualdad legal" column to float
df_merged_2['índice de igualdad legal'] = df_merged_2['índice de igualdad legal'].astype(float)

/tmp/ipykernel_17821/650601772.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_2['índice de igualdad legal'] = df_merged_2['índice de igualdad legal'].astype(float)

In [68]:
# Convert the data type of the "fecha_despenalización" column to integer
df_merged_2['fecha_despenalización'] = df_merged_2['fecha_despenalización'].astype(int)

/tmp/ipykernel_17821/2154988808.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_2['fecha_despenalización'] = df_merged_2['fecha_despenalización'].astype(int)

In [69]:
df_merged_2.dtypes

país                            object
índice de igualdad legal       float64
legalidad_colectivo_lgbtiq+     object
fecha_despenalización            int64
pena_máxima                     object
constitución                    object
protección_amplia               object
empleo                          object
crimen_odio                     object
incitación                      object
prohibición_terapias            object
matrimonio_igualitario          object
uniones_civiles                 object
adopción_conjunta               object
adopción_segundo_progenitor     object
dtype: object

In [70]:
df_merged_2.head(10)

,país,índice de igualdad legal,legalidad_colectivo_lgbtiq+,fecha_despenalización,pena_máxima,constitución,protección_amplia,empleo,crimen_odio,incitación,prohibición_terapias,matrimonio_igualitario,uniones_civiles,adopción_conjunta,adopción_segundo_progenitor
0,Afghanistan,0.00,No,0,Pena de muerte,No,No,No,No,No,No,No,No,No,No
2,Albania,62.27,Si,1995,Desconocido,No,Si,Si,Si,Si,No,No,No,No,No
3,Algeria,3.42,No,0,2 años,No,No,No,No,No,No,No,No,No,No
5,Andorra,85.71,Si,1990,Desconocido,No,Si,Si,Si,No,No,No,Si,Si,Si
6,Angola,66.19,Si,2021,Desconocido,No,Si,Si,Si,Si,No,No,No,No,No
8,Antigua and Barbuda,84.21,No,0,15 años,No,No,No,Limitada,No,No,No,No,No,No
9,Argentina,87.17,Si,1903,Desconocido,No,Limitada,Limitada,Si,No,Limitada,Si,Si,Si,Si
10,Armenia,47.73,Si,2003,Desconocido,No,No,No,No,No,No,No,No,No,No
13,Australia,89.65,Si,1997,Desconocido,No,Si,Si,Limitada,Si,Limitada,Si,Si,Si,Si
14,Austria,92.96,Si,1971,Desconocido,No,Si,Si,Si,Si,No,Si,Si,Si,Si

In [71]:
df_merged_2.to_csv('LegalidadLGTBIQA+.csv')